sudo: required
services:
  - docker

before_install:
    - docker build -t manpreet1605/docker-react -f Dockerfile.dev .

script:
 - docker run manpreet1605/docker-react npm run test -- --coverage
  