sudo: required
services:
  - docker

before_install:
  - docker build -t docker-new -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-new npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  name: "docker-new"
  env: "Dockernew-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-384802646453"
  bucket_path: "docker-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
