sudo: required
services:
  - docker

before_install:
  - docker build -t manpreet/docker-new -f Dockerfile.dev .

script:
  - docker run -e CI=true manpreet/docker-new npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  name: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-384802646453"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"